# Generated by Django 3.2.9 on 2022-01-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=True, verbose_name='يعمل'),
        ),
        migrations.AddField(
            model_name='store',
            name='image_store',
            field=models.ImageField(blank=True, upload_to='Stores/MainPic', verbose_name='صورة الفرع'),
        ),
        migrations.AddField(
            model_name='store',
            name='monthly_visited',
            field=models.BooleanField(default=True, verbose_name='زيارة شهرية'),
        ),
        migrations.AddField(
            model_name='store',
            name='name_area',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='اسم المنطقة'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='FixRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=200, verbose_name='وصف قصير للمشكلة')),
                ('admen_aman', models.CharField(max_length=200, verbose_name='الادمن المسئول')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='تايخ الطلب')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='اخر تعديل')),
                ('monthly_visited', models.BooleanField(default=True, verbose_name='مع الزيارة الشهرية')),
                ('emergency', models.CharField(blank=True, max_length=100, null=True, verbose_name='درجة الأهمية')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.store', verbose_name='الفرع')),
            ],
        ),
        migrations.CreateModel(
            name='AdmenAman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('mobile_num', models.CharField(max_length=11, verbose_name='رقم الموبايل')),
                ('mobile_num2', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم الموبايل 2')),
                ('name_area', models.CharField(blank=True, max_length=20, null=True, verbose_name='اسم المنطقة')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aman.tags', verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='admen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aman.admenaman', verbose_name='ادمين الفرع حاليا'),
        ),
        migrations.AddField(
            model_name='store',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aman.tags', verbose_name='Tag'),
        ),
    ]
