# Generated by Django 3.2.9 on 2022-01-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0002_auto_20220131_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixrequest',
            name='emergency',
            field=models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Postpone', 'Postpone')], max_length=100, null=True, verbose_name='درجة الأهمية'),
        ),
    ]
