# Generated by Django 3.2.9 on 2022-02-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0004_auto_20220201_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixrequest',
            name='admen_aman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.admenaman', verbose_name='الادمن المسئول'),
        ),
    ]
