# Generated by Django 3.2.9 on 2022-02-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0006_auto_20220201_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='tag',
        ),
        migrations.AddField(
            model_name='store',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='aman.Tags', verbose_name='Tag'),
        ),
    ]
