# Generated by Django 3.2.9 on 2022-02-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0007_auto_20220201_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address_store',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='store',
            name='location_store',
            field=models.URLField(blank=True, null=True, verbose_name='الموقع'),
        ),
    ]
