# Generated by Django 3.2.9 on 2022-02-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0008_auto_20220201_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='store',
            name='line',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط السير'),
        ),
    ]
