# Generated by Django 3.2.9 on 2022-02-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0011_alter_store_image_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='يعمل'),
        ),
        migrations.AlterField(
            model_name='store',
            name='monthly_visited',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='زيارة شهرية'),
        ),
    ]
