# Generated by Django 3.2.9 on 2022-02-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0012_auto_20220201_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='admenaman',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='الايميل'),
        ),
    ]
