# Generated by Django 3.2.9 on 2022-02-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0015_alter_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القطعة-الخدمة')),
                ('type_parent', models.CharField(choices=[('دهانات', 'دهانات'), ('تركيبات', 'تركيبات'), ('كهرباء', 'كهرباء'), ('زجاج', 'زجاج'), ('تكييف', 'تكييف'), ('نقل', 'نقل'), ('معاينة', 'معاينة'), ('رفع مقاسات', 'رفع مقاسات')], max_length=100, verbose_name='النوع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Items/', verbose_name='صورة القطعة')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='content',
            field=models.ManyToManyField(to='aman.Item', verbose_name='الوحدة'),
        ),
    ]
