# Generated by Django 3.2.9 on 2022-02-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0016_auto_20220205_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_parent',
            field=models.CharField(choices=[('دهانات', 'دهانات'), ('قطع غيار', 'قطع غيار'), ('تركيبات', 'تركيبات'), ('كهرباء', 'كهرباء'), ('زجاج', 'زجاج'), ('تكييف', 'تكييف'), ('نقل', 'نقل'), ('معاينة', 'معاينة'), ('رفع مقاسات', 'رفع مقاسات')], max_length=100, verbose_name='النوع'),
        ),
    ]
