# Generated by Django 3.2.9 on 2022-02-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0020_alter_visit_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='اسم الفرع'),
        ),
    ]
