# Generated by Django 3.2.9 on 2022-02-06 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aman', '0025_auto_20220206_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم الاول')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللقب')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم التليفون')),
                ('phone_number2', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم التليفون 2')),
                ('addres', models.CharField(blank=True, max_length=300, null=True, verbose_name='العنوان')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='المنقطة')),
                ('mailo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ايميل (بالشركة)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Profiles/', verbose_name='صورة شخصية')),
                ('stores', models.ManyToManyField(to='aman.Store', verbose_name='الفروع المسئول عنها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
