# Generated by Django 3.2.9 on 2022-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0028_alter_profile_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pos_in_store',
            field=models.CharField(blank=True, choices=[('aman_admin', 'Admin'), ('aman_manager', 'Manager'), ('quality', 'Quality'), ('technical', 'Technical'), ('staff', 'staff')], max_length=50, null=True, verbose_name='صفته بالموقع'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المسمى الوظيفى'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stores',
            field=models.ManyToManyField(blank=True, to='aman.Store', verbose_name='الفروع المسئول عنها'),
        ),
    ]
